### ISSUE TITLE
DRQN-AttributeError: 'zip' object has no attribute 'append'

### ISSUE THREAD

**Issue by silentobservers** [awjuliani/DeepRL-Agents#56]
I run the code and meet a problem like this:
*********************************************************
Target Set Success
5000 0.65 1
 98%|█████████████████████████████████████████▏| 50/51 [00:00<00:00, 665.63it/s]
Traceback (most recent call last):
  File "Deep_Recurrent_Q-Network.py", line 235, in <module>
    summaryLength,h_size,sess,mainQN,time_per_step)
  File "/home/jimmy/desktop/tensorflowcode/DRL/helper.py", line 52, in saveToCenter
    images.append(bufferArray[-1,3])
AttributeError: 'zip' object has no attribute 'append'
************************************************************
I have no idea to solve it and need a help, my friends.
Thanks a lot.

**Comment by paulsimvient** [comment]
same issue here.

**Comment by thortom** [comment]
I suspect that you are running this with Python3, then the zip() returns an iterator see here: https://docs.python.org/3/library/functions.html#zip to fix this you could change line 51 in helper.py to
`images = list(zip(bufferArray[:,0]))`
